### ISSUE TITLE
Why not contribute to optics?

### ISSUE THREAD

**Issue by arybczak** [cmk/profunctor-optics#10]
Hey,

I'm not sure if you're aware, but there already exists an implementation of profunctor optics matching `lens` in power - https://github.com/well-typed/optics (and having advantages such as using newtype instead of bare profunctor transformations for better error messages or having support for overloaded labels). You can see https://www.well-typed.com/blog/2019/09/announcing-the-optics-library/ for general overview.

Unless you're developing this package to further your own understanding of things, I think it would be beneficial to avoid duplication of effort and join forces (unless your package somewhat deviates from what aims of the `optics` library are, I haven't looked very closely).

**Comment by cmk** [comment]
Thanks, yeah thats a great question. I'm aware of the library and sympathetic to the benefits of pooling effort and not fragmenting ecosystems. I [asked you](https://www.reddit.com/r/haskell/comments/cyo4o2/welltyped_announcing_the_optics_library/eyucxeb/?context=3) a similar question about `profunctors` when the announcement came out.

That said, the goals and approach of this project are quite different from those of `optics`. For example this project aims to be interoperable, meaning one should only need the classes in `profunctors` to make optics, and no special functions to compose them.
