### ISSUE TITLE
Questions about Traversal and Setter

### ISSUE THREAD

**Issue by YPares** [cmk/profunctor-optics#26]
Hi!
I noticed that Traversal has the following signature:

`type Traversal s t a b = forall p. (Choice p, Strong p, Representable p, Applicative (Rep p)) => Optic p s t a b`

is there a reason for the `Representable` requirement? Would it be possible to express it as

`type Traversable s t a b = forall p. Traversing p => Optic p s t a b`
?
(Traversing being in `profunctors`)

The `Representable` condition in `Setter` and `Traversal` is kind of problematic, as it prevents to instantiate `p` to some arrow that isn't directly `Kleisli` or `Star`.
I'm specifically interested in `Cayley`, which cannot be an instance of `Representable` but for which an instance of `Traversing` can be written ( @guaraqe just added it to `profunctors`, it has just been merged ).

**Comment by cmk** [comment]
Hey @YPares sorry for the delayed response.

The reason I chose not to express the constraint the way you describe is that doing so would require a plethora of new type classes to handle all of the [downstream optics](https://github.com/cmk/profunctor-optics/blob/master/profunctor-optics/src/Data/Profunctor/Optic/Types.hs#L209-L303) that are equivalent to `Representable` or `Corepresentable` plus some constraint on the representing functor (e.g. `Traversing1`, `Cotraversing`, etc). 

This would complicate the API, require many new orphans (or changes to `profunctors`), increase the maintenance burden, and limit forwards compatibility. An example of the last point is [here](https://github.com/cmk/profunctor-optics/blob/master/profunctor-optics/src/Data/Profunctor/Optic/Machine.hs) (described in [this paper](https://arxiv.org/abs/2001.07488) as algebraic lenses).

After prototyping it both ways I felt that a good balance was to make the cut after the affine optics.
